### ISSUE TITLE
claudie scale out

### ISSUE THREAD

**Issue by gedw99** [MiroslavRepka/MiroslavRepka#2]
I am using Claudie and its awesome

I have also been using https://github.com/choria-io for scaleout of non k8 stuff.

Its designed to managed 10000 servers and keep them in sync. Its all golang.

I noticed that it can be used with Claudie in that it can manage Claudie and Claudie agents.

**Comment by MiroslavRepka** [comment]
Hey @gedw99 thanks for reaching out!

I will check out the project and I will share it with the rest of the team. In the meantime, If you have any questions, let me know and I will be happy to assist you :).

**Comment by gedw99** [comment]
Sorry but I avoid slack

**Comment by MiroslavRepka** [comment]
Sure, that's understandable. Could you maybe describe it here? We are very interested in the feedback from the community. :)

**Comment by gedw99** [comment]
You can grab me on telegram . It’s on my GitHub profile 

happy to discuss etc :)
